export const TXT_BLOG_NAME = "Cryptsu";
export const TXT_NAV_HOME = "/home";
export const TXT_NAV_TEST = "/test";
export const TXT_NAV_POSTS = "/posts";
export const TXT_CODE_IS_HIDDEN = "... hidden ...";
export const TXT_TOC = "Table Of Content";
export const TXT_WORDS = "words";
export const TXT_MIN_READ = 'mins';
export const TXT_FOOTER = "::: Made with ❤️ by Mistsu :::"
export const TXT_AUTHOR_DESC = "Hi everyone :) I'm a newbie crypto player who loves to share knowledge through writeups.";
export const TXT_BLINK_CHAR = "▌";
export const TXT_NO_DESCRIPTION = "(no description is given)"
export const TXT_POSTS = "Posts";